trigger: none

steps: 
  - bash: echo $(System.TeamProject) -- $(System.Debug)
  - bash: echo $(Release.EnvironmentName) -- $(Release.Reason)
  - bash: echo $(Agent.HomeDirector)  -- $(Release.Artifacts.{az_group}.DefinitionName)
