steps:
    - bash: |
        escape_data() {
          local data=$1
          data="${data//'%'/'%AZP25'}"
          data="${data//$'\n'/'%0A'}"
          data="${data//$'\r'/'%0D'}"
          echo "$data"
        }
        echo "##vso[task.setvariable variable=myStageVal;isOutput=true]$(escape_data $'foo\nbar')"
      name: MyOutputVar