steps:
  - bash: echo This script could use $SYSTEM_ACCESSTOKEN

  - powershell: | 
      Write-Host "This is a script that could use $env:ASYSTEM_ACCESSTOKEN"
      Write-Host "$env:ASYSTEM_ACCESSTOKEN = $(System.AccessToken)"
     
    env:
      ASYSTEM_ACCESSTOKEN: $(System.AccessToken)