variables:
  a1: aaaa
  b1: bbbb
parameters:
  - name: pa1
    type: string
    default: pastring
pool:
  vmimage: windows-latest
  
trigger: none

steps: 
  #- powershell: write-host "agent os is -$(Agent.OS)-"
  - pwsh:  echo "agent os is -$(Agent.OS)-"
  - pwsh: echo "##vso[task.setvariable variable=sauce]crushed vvvv tomatoes"
  - pwsh: write-host No problem reading $env:SAUCE - $(sauce)
  - pwsh: echo reading $SAUCE - $(sauce)
