jobs:

# Set an output variable from a job with slicing
- job: A
  pool:
    vmImage: 'ubuntu-18.04'
    parallel: 1 # Two slices
  steps:
  - bash: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the slice $(system.jobPositionInPhase) value"
    name: setvarStep
  - script: echo $(setvarStep.myOutputVar)
    name: echovar

# Map the variable from the job for the first slice
- job: B
  dependsOn: A
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    myVarFromJobsA1: $[ dependencies.A.outputs['job1.setvarStep.myOutputVar'] ]
    myVarFromJobsA0: $[ dependencies.A1.outputs['setvarStep.myOutputVar'] ]
    myVarFromJobsA: $[ dependencies.A.outputs['setvarStep.myOutputVar'] ]
  steps:
  - script: |
       echo $(myVarFromJobsA1)
       echo $(myVarFromJobsA0)
       echo $(myVarFromJobsA)
    name: echovar