variables:
  a1: aaaa
  b1: bbbb
parameters:
  - name: pa1
    type: string
    default: pastring
pool:
  vmimage: windows-latest
  
trigger: none

steps: 
  - powershell: echo "agent os is -$(Agent.OS)-"
  - powershell: echo "##vso[task.setvariable variable=sauce]crushed tomatoes"
  - powershell: write-host "No problem reading $env:SAUCE"
