variables:
 GLOBAL_MYSECRET: $(mySecret) # this will not work because the secret variable needs to be mapped as env
 GLOBAL_MY_MAPPED_ENV_VAR: $(nonSecretVariable) # this works because it's not a secret.

pool:
  vmimage: ubuntu-latest
  #name: my-win-pool

steps:
- task: PowerShell@2
  inputs:
    targetType: inline
    script: 'dir'
- powershell: write-host "the work dir is $(Build.SourcesDirectory) "
