pool:
  #vmImage: windows-latest
  name: my-win-pool

trigger:
  none

jobs:
- job: build_VirW
  variables:
  - group: dev_us-east-1
  - name: job_name
    value: 'Build us-east-1'
  steps:
    - script: |
        echo $(job_name)
        echo %REGION%
        echo $( STATE_BUCKET)
        echo $(INSTANCE_SIZE)
      displayName: 'Show Variable Values'
