

pool:
  #vmimage: ubuntu-latest
  name: my-win-pool

steps:
- task: MyTask@1  # this step generates the output variable
  name: ProduceVar  # because we're going to depend on it, we need to name the step
  inputs:
    myVar: "what is it?"   